### ISSUE TITLE
Validate v1.0.3

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-release#109]
Validate dcrinstall upgrades on the following platforms:
- [x] Linux
- [x] Windows
- [x] OSX

Validate dcrinstall clean install on the following platforms:
- [x] Linux
- [x] Windows
- [x] OSX

Please comment with what you tested.  Multiple linuxes are always welcome.

**Comment by jolan** [comment]
(Arch) Linux 64-bit upgrade and clean install both worked for me.

**Comment by jolan** [comment]
Windows 10 64-bit upgrade and clean install both worked for me.

**Comment by alexlyp** [comment]
linux amd64 tOK

**Comment by jcvernaleo** [comment]
osx worked fine in both cases.

**Comment by jcvernaleo** [comment]
I think that covers all so closing.
