### ISSUE TITLE
validate v1.0.5

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-release#112]
Need fresh install and upgrade
- [x] windows
- [x] linux
- [x] osx

**Comment by jolan** [comment]
(Arch) Linux upgrade/install worked OK.
Windows 10 64-bit upgrade/install worked OK.

**Comment by jcvernaleo** [comment]
Ubuntu 16.04 worked in both cases too.

**Comment by jcvernaleo** [comment]
OSX also looked good in both tests.

**Comment by jcvernaleo** [comment]
Covered all our systems, so closing.
