### ISSUE TITLE
Automatic Wallet Creation Conditional

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/decred-release#115]
Currently, if **none** of the .conf files exist **AND** a wallet.db doesn't already exist, then --create is started. Why not only check for ../dcrwallet/mainnet/wallet.db?

**Comment by jcvernaleo** [comment]
That makes sense to me (well, checking for `$NETWORK/wallet.db`).

@marcopeereboom you wrote that code initially, do you have an opinion?

**Comment by marcopeereboom** [comment]
Fixed
