### ISSUE TITLE
have project name in the file name

### ISSUE THREAD

**Issue by raedah** [decred/decred-release#13]
instead of 
linux-amd64-20160318-01.tar.gz
have
decred-v0.1.0-linux-amd64-20160318-01.tar.gz
or even just
decred-v0.1.0-linux-amd64.tar.gz

**Comment by jrick** [comment]
We can add "decred" and version number to the files, but why would you want to remove the date?

**Comment by alexlyp** [comment]
Yah agree that we should add decred and leave the date

**Comment by jolan** [comment]
Also agree with adding decred and keeping the date/build number.

YYYYMMDD-NN is there to provide extra version information in case the binaries aren't built properly and we need to release new ones.  It's also a nice indicator of how recent the release is.
