### ISSUE TITLE
A problem with dcrinstall-linux-arm64-v1.1.2

### ISSUE THREAD

**Issue by Arriu** [decred/decred-release#136]
I've Downloaded dcrinstall-linux-arm64-v1.1.2, verified the manifest and the sha256sum.
Then i made it an executable and ran ./dcrinstall-linux-arm64-v1.1.2
which gave me the following error message: 

bash: ./dcrinstall-linux-arm64-v1.1.2: cannot execute binary file: Exec format error

when i ran sudo ./dcrinstall-linux-arm64-v1.1.2 the error message ran:

./dcrinstall-linux-arm64-v1.1.2: 1: ./dcrinstall-linux-arm64-v1.1.2: Syntax error: ")" unexpected

I'm doing this an a Raspberry pi 3.

When i proceeded by trying to install the 32-bit version, it worked flawlessly

**Comment by jolan** [comment]
The Raspberry Pi 3 does have a 64-bit CPU but you're running a 32-bit OS on it so this is expected behavior.

**Comment by Arriu** [comment]
Thanks alot for clearing that up, should i delete this issue can you guys close this ?

**Comment by Arriu** [comment]
Thanks alot for clearing this up
