### ISSUE TITLE
Unable to set up dcrinstall-linux-arm-v1.2.0 on Raspberry pi 3 (Raspbian)

### ISSUE THREAD

**Issue by yoritomoto** [decred/decred-release#141]
Hello,

Please bear with me as I am very new to this process.

I am currently trying to set up dcrinstall-linux-arm-v1.2.0 on Raspberry pi 3 (Raspbian).

When I try and make this file executable on the terminal program, by running 
cd ~/Downloads/, then:
chmod u+x dcrinstall-linux-arm-v1.2.0

I get an error saying
"chmod: cannot access 'dcrinstall-linux-arm-v1.2.0': No such file or directory

What am I missing?

**Comment by unlimittt** [comment]
```
cd ~
wget https://github.com/decred/decred-release/releases/download/v1.2.0/dcrinstall-linux-arm-v1.2.0
chmod u+x dcrinstall-linux-arm-v1.2.0
./dcrinstall-linux-arm-v1.2.0
```
Try to start dcrd:
`./decred/dcrd`
It will sync with network. Can take more than 1 day. Config files locate in ~/.dcrd/dcrd.conf and ~/.dcrwallet/dcrwallet.conf

If you want to make a background running daemon:
```
sudo touch /etc/systemd/system/dcrd.service
sudo vi /etc/systemd/system/dcrd.service
```
and paste (Shift + Insert) then type :wq and press Enter
```
[Unit]
Description=dcrd
After=network.target

[Service]
User=pi
ExecStart=/home/pi/decred/dcrd

[Install]
WantedBy=multi-user.target
```

To start dcrd:
`sudo systemctl start dcrd`
To stop dcrd:
`sudo systemctl stop dcrd`
To check what's going on:
`systemctl status dcrd -l`
To enable start automatically on system boot:
sudo systemctl enable dcrd
To disable autostart:
`sudo systemctl disable dcrd`

Do the same for dcrwallet:
```
sudo touch /etc/systemd/system/dcrwallet.service
sudo vi /etc/systemd/system/dcrwallet.service
```
paste:
```
[Unit]
Description=dcrwallet
After=network.target

[Service]
User=pi
ExecStart=/home/pi/decred/dcrwallet --reuseaddresses --automaticrepair 
# --walletpass nopass2941 - add it in the end if your wallet has public password

[Install]
WantedBy=multi-user.target
```
