### ISSUE TITLE
Unable to connect the dcrd's RPC server form another  machine

### ISSUE THREAD

**Issue by grayfoxd** [decred/decred-release#145]
hi,
I have used two methods to connect the RPC server:
1.edit the dcrd.conf , use the RPC user and password; add RPC port 0.0.0.0:9109
2.start dcrd with the RPC info, like  
`./dcrd --rpcuser=xxxxx --rpcpass=xxxxx --rpclisten=0.0.0.0:9109`

I can't use dcr mining pool to  connect it form another machine  . 
I am sure  that port is Available。

Thanks for your help！

**Comment by chappjc** [comment]
You don't need to open a second issue to fix typos in the first: https://github.com/decred/decred-release/issues/144.
Also, github issues are not meant to be a support/helpdesk system.  If you need help setting things up, please use one of the chat platforms listed at https://www.decred.org/community/
