### ISSUE TITLE
RPCS: Configuration: No payment addresses specified via --miningaddr

### ISSUE THREAD

**Issue by peteim** [decred/decred-release#146]
when i use yiimp pool connect dcrdwallet,  dcrd make error: RPCS: Configuration: No payment addresses specified via --miningaddr
Has the dcrdwallet version changed ? or command "getwork" changed ? thanks for your answer

**Comment by davecgh** [comment]
It has not changed.  You need to launch dcrd with `--miningaddr` so it knows where to send the mined coins.

**Comment by peteim** [comment]
> It has not changed. You need to launch dcrd with `--miningaddr` so it knows where to send the mined coins.

Thank you . according to your method, my local computer can be successfully minerd.
