### ISSUE TITLE
Decredliton 1.4.0

### ISSUE THREAD

**Issue by nshan74** [decred/decred-release#149]
Hello, help please, please, five days can not install the wallet, my version 1.3 worked well, wanted to update, see what happened, I ask You to help. Thanks.
[ERR] DCRD: metadata claims file 5, offset 482740795, but block data is at file 0, offset 0
2019-03-30 13:00:20.359 [INF] DCRD: Shutdown complete

internal/process/warning.js:18 (node:14716) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

![111111111111](https://user-images.githubusercontent.com/35377859/55274811-ad50ef00-52ed-11e9-8f81-7f74595ac278.png)
![22222222222](https://user-images.githubusercontent.com/35377859/55274815-bb067480-52ed-11e9-92dc-c9171f93c74b.png)

**Comment by marcopeereboom** [comment]
This issue should have been fixed in subsequent releases.
