### ISSUE TITLE
dcrinstall ignore argument -path

### ISSUE THREAD

**Issue by joijuke** [decred/decred-release#166]
execute dcrinstall -path /home/foo/download_path , dcrinstall output log:

11:10:24.932 temporary directory: /tmp/decred155921598
11:10:24.932 downloading manifest: https://github.com/decred/decred-binaries/releases/download/v1.5.0/decred-v1.5.0-manifest.txt

temporary directory: /tmp/decred155921598
ignore argument -path

**Comment by marcopeereboom** [comment]
Per the documentation, you must add `-skip`.
