### ISSUE TITLE
Request: Add VERSION file

### ISSUE THREAD

**Issue by AlanBarber** [decred/decred-release#17]
It would be nice to have a VERSION file in the release master branch that includes the current releases info.  I was thinking a json file that includes version, date and build number something like:

{
    "decred": {
        "version": "0.1.2",
        "build": "01",
        "date": "2016-05-03"
    },
    "paymetheus": {
        "version": "0.0.8"
    },
    "miners": {
        "version": "0.1.0"
    }
}

This would provide all the info needed to create automated tools to check for and update the different software being released.

**Comment by jcvernaleo** [comment]
I kind of like that idea.  Would be nice if the builds scripts could do it automatically but I can live with doing it by hand.  I'll do a PR with something.  I guess json is the way to go for now.

**Comment by AlanBarber** [comment]
Thanks for doing this. It will come in very handy!
