### ISSUE TITLE
ambiguous folder name

### ISSUE THREAD

**Issue by raedah** [decred/decred-release#19]
Similar to closed issue #13, uncompressing the archive
decred-v0.1.2-linux-amd64-20160503-01.tar.gz
just gives you a directory just called
~/linux-amd64/
Better would be any of these
decred-v0.1.2-linux-amd64-20160503-01
decred-v0.1.2-linux-amd64
decred-v0.1.2-linux
decred-v0.1.2
decred

**Comment by chappjc** [comment]
Since the file name has the details on version and date, and having this repeated in a folder within the archive makes scripting that much more difficult, I feel strongly that the folder should be the same from version to version.  I'm fine with it as is, but decred-linux-amd64 is also good.

**Comment by jolan** [comment]
I agree. I would prefer adding the version/build to the directory. That way it doesn't overwrite old extracted versions. 99% of FOSS archives seem to be structured this way.

**Comment by chappjc** [comment]
Take Go, for instance.  The archive just contains a folder called "go".  In a deploy script, you just give the URL to the tar.gz, but it's all the same after that.  Just copy/move "go".

**Comment by jcvernaleo** [comment]
I admit the current folder names are less than ideal.  That said I think I agree with @chappjc and would lean towards names like: decred-freebsd-arm as the name inside the tarball.

**Comment by alexlyp** [comment]
yah i like decred-(OS)-(arch)
