### ISSUE TITLE
remove bitcoin core download and make --dcrdex enabled by default

### ISSUE THREAD

**Issue by chappjc** [decred/decred-release#227]
Bitcoin Core is not required or even recommended for most users.  Downloading and configuration of it can be removed.

Also, most people just double click the dcrinstall program and this does not run with the `--dcrdex` switch so they don't get DEX support unless they open a console and type in the command with said switch.  We can just have it install dcrdex by default now that the Bitcoin Core stuff is not needed.

**Comment by bgptr** [comment]
on this

**Comment by chappjc** [comment]
I'm doing most of it in https://github.com/decred/decred-release/pull/228, at least I think.

I need to refresh my memory on building and testing dcrinstall, so it's in draft for now.  Otherwise, I have no further changes planned for it.

**Comment by bgptr** [comment]
@chappjc ohh... my bad, I wanted to comment in https://github.com/decred/decrediton/issues/3793
