### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by 0xmichalis** [decred/decred-release#37]
https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by jcvernaleo** [comment]
Thanks.  That was an oversight.  Will fix now.

**Comment by 0xmichalis** [comment]
@jcvernaleo shouldn't it be in the top directory instead of cmd/dcrinstall?

**Comment by jcvernaleo** [comment]
@kargakis I'm not sure.  The top level doesn't have any code in it.  I would think the license would go with the code but I could be wrong.
