### ISSUE TITLE
dcrinstall not working on OS X

### ISSUE THREAD

**Issue by girino** [decred/decred-release#51]
Logs shows: 
02:08:31.173 user: Current not implemented on darwin/amd64

Googling fot it i found that this is caused by cross compiling: https://github.com/golang/go/issues/6376#issuecomment-66085388

So dcrinstall for OSX (darwin) should be compiled under OSX, or avoid using user.Current().

**Comment by jolan** [comment]
Thanks for reporting, we hit this issue on arm64 too but didn't realize it's a problem on OSX and potentially other platforms.

**Comment by jcvernaleo** [comment]
I just tried this on a mac, and I can confirm it.  @marcopeereboom did you have another way you could do do this that is more crossplatform?
