### ISSUE TITLE
Verify all OS'

### ISSUE THREAD

**Issue by marcopeereboom** [decred/decred-release#54]
Verify that dcrinstall works on thre following OS':
- [x] OpenBSD/Bitrig
- [x] Linux
- [x] OSX
- [x] Windows

Make sure dcrd, dcrctl, dcrwallet and dcrticketbuyer work.  Click on check box once verified.

Additionally check:
- [x] Windows gominer
- [x] Linux gominer

**Comment by jolan** [comment]
- [x] Windows gominer
- [x] Linux gominer
- [x] Linux dcrinstall clean install
- [x] Linux dcrinstall upgrade
- [x] Windows dcrinstall clean install
- [x] Windows dcrinstall upgrade

**Comment by jcvernaleo** [comment]
Tested dcrinstaller, dcrd, dcrwallet, dcrticketbuyer, dcrctl on osx amd64, linux-amd64, and bitrig-amd64.
Running dcrd and dcrwallet on linux-arm as well.
Tested gominer on linux.

All perform as expected.

**Comment by marcopeereboom** [comment]
Thanks.
