### ISSUE TITLE
Validate upgrade from prior version.

### ISSUE THREAD

**Issue by marcopeereboom** [decred/decred-release#60]
Validate dcrinstall upgrades on the following platforms:
- [x] Linux
- [x] Windows
- [x] OSX

Validate dcrinstall clean install on the following platforms:
- [x] Linux
- [x] Windows
- [x] OSX

**Comment by jcvernaleo** [comment]
Clean install on linux worked.

**Comment by jcvernaleo** [comment]
Linux upgrade too.

**Comment by jcvernaleo** [comment]
osx upgrade and clean both worked.

**Comment by jolan** [comment]
Windows upgrade and clean work.  Re-tested linux clean/upgrade too.

**Comment by jcvernaleo** [comment]
I tested win7, osx, and linux again (clean and upgrade) and all seem good with the latest master.

**Comment by marcopeereboom** [comment]
Wrong release you guys :)

This was for the next version so that we don't miss it!  But, I'll move it to 0.4.0 and make a new 0.5.0 one.

**Comment by jcvernaleo** [comment]
@marcopeereboom you made a testing issue and we got excited and started testing :)
