### ISSUE TITLE
Validate 0.8.0 release

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-release#84]
Validate dcrinstall upgrades on the following platforms:
- [ ] Linux
- [ ] Bitrig
- [ ] Windows
- [ ] OSX

Validate dcrinstall clean install on the following platforms:
- [ ] Linux
- [ ] Bitrig
- [ ] Windows
- [ ] OSX

**Comment by jcvernaleo** [comment]
cmd line tools look fine on OSX

**Comment by alexlyp** [comment]
bins are good for linux 64

**Comment by jcvernaleo** [comment]
bitrig too

**Comment by jcvernaleo** [comment]
@jolan said he tested the actual installer so I think we got the coverage we need here.
